// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vector_tile.proto

package vectortile

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Tile_GeomType int32

const (
	Tile_UNKNOWN    Tile_GeomType = 0
	Tile_POINT      Tile_GeomType = 1
	Tile_LINESTRING Tile_GeomType = 2
	Tile_POLYGON    Tile_GeomType = 3
)

var Tile_GeomType_name = map[int32]string{
	0: "UNKNOWN",
	1: "POINT",
	2: "LINESTRING",
	3: "POLYGON",
}

var Tile_GeomType_value = map[string]int32{
	"UNKNOWN":    0,
	"POINT":      1,
	"LINESTRING": 2,
	"POLYGON":    3,
}

func (x Tile_GeomType) Enum() *Tile_GeomType { _ = "STUB: not implemented"; return nil }

func (x Tile_GeomType) String() string { _ = "STUB: not implemented"; return "" }

func (x *Tile_GeomType) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

func (Tile_GeomType) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type Tile struct {
	Layers                       []*Tile_Layer `protobuf:"bytes,3,rep,name=layers" json:"layers,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}      `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Tile) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Tile) String() string            { _ = "STUB: not implemented"; return "" }
func (*Tile) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Tile) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var extRange_Tile = []proto.ExtensionRange{
	{Start: 16, End: 8191},
}

func (*Tile) ExtensionRangeArray() []proto.ExtensionRange { _ = "STUB: not implemented"; return nil }

func (m *Tile) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Tile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Tile) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Tile) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Tile) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Tile proto.InternalMessageInfo

func (m *Tile) GetLayers() []*Tile_Layer { _ = "STUB: not implemented"; return nil }

// Variant type encoding
type Tile_Value struct {
	// Exactly one of these values may be present in a valid message
	StringValue                  *string  `protobuf:"bytes,1,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	FloatValue                   *float32 `protobuf:"fixed32,2,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	DoubleValue                  *float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	IntValue                     *int64   `protobuf:"varint,4,opt,name=int_value,json=intValue" json:"int_value,omitempty"`
	UintValue                    *uint64  `protobuf:"varint,5,opt,name=uint_value,json=uintValue" json:"uint_value,omitempty"`
	SintValue                    *int64   `protobuf:"zigzag64,6,opt,name=sint_value,json=sintValue" json:"sint_value,omitempty"`
	BoolValue                    *bool    `protobuf:"varint,7,opt,name=bool_value,json=boolValue" json:"bool_value,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Tile_Value) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Tile_Value) String() string            { _ = "STUB: not implemented"; return "" }
func (*Tile_Value) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Tile_Value) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var extRange_Tile_Value = []proto.ExtensionRange{
	{Start: 8, End: 536870911},
}

func (*Tile_Value) ExtensionRangeArray() []proto.ExtensionRange {
	_ = "STUB: not implemented"
	return nil
}

func (m *Tile_Value) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Tile_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Tile_Value) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Tile_Value) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Value) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Tile_Value proto.InternalMessageInfo

func (m *Tile_Value) GetStringValue() string { _ = "STUB: not implemented"; return "" }

func (m *Tile_Value) GetFloatValue() float32 { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Value) GetDoubleValue() float64 { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Value) GetIntValue() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Value) GetUintValue() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Value) GetSintValue() int64 { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Value) GetBoolValue() bool { _ = "STUB: not implemented"; return false }

type Tile_Feature struct {
	Id *uint64 `protobuf:"varint,1,opt,name=id,def=0" json:"id,omitempty"`
	// Tags of this feature are encoded as repeated pairs of
	// integers. Even indexed values (n, beginning with 0) are
	// themselves indexes into the layer's keys list. Odd indexed
	// values (n+1) are indexes into the layer's values list.
	// The first (n=0) tag of a feature, therefore, has a key of
	// layer.keys[feature.tags[0]] and a value of
	// layer.values[feature.tags[1]].
	Tags []uint32 `protobuf:"varint,2,rep,packed,name=tags" json:"tags,omitempty"`
	// The type of geometry stored in this feature.
	Type *Tile_GeomType `protobuf:"varint,3,opt,name=type,enum=vector_tile.Tile_GeomType,def=0" json:"type,omitempty"`
	// Contains a stream of commands and parameters (vertices). The
	// repeat count is shifted to the left by 3 bits. This means
	// that the command has 3 bits (0-7). The repeat count
	// indicates how often this command is to be repeated. Defined
	// commands are:
	// - MoveTo:    1   (2 parameters follow)
	// - LineTo:    2   (2 parameters follow)
	// - ClosePath: 7   (no parameters follow)
	//
	// Commands are encoded as uint32 varints. Vertex parameters
	// are encoded as deltas to the previous position and, as they
	// may be negative, are further "zigzag" encoded as unsigned
	// 32-bit ints:
	//
	//   n = (n << 1) ^ (n >> 31)
	//
	// Ex.: MoveTo(3, 6), LineTo(8, 12), LineTo(20, 34), ClosePath
	// Encoded as: [ 9 6 12 18 10 12 24 44 15 ]
	//               |       |              `> [00001 111] command type 7 (ClosePath), length 1
	//               |       |       ===== relative LineTo(+12, +22) == LineTo(20, 34)
	//               |       | ===== relative LineTo(+5, +6) == LineTo(8, 12)
	//               |       `> [00010 010] = command type 2 (LineTo), length 2
	//               | ==== relative MoveTo(+3, +6)
	//               `> [00001 001] = command type 1 (MoveTo), length 1
	//
	// The original position is (0,0).
	Geometry             []uint32 `protobuf:"varint,4,rep,packed,name=geometry" json:"geometry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tile_Feature) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Tile_Feature) String() string            { _ = "STUB: not implemented"; return "" }
func (*Tile_Feature) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Tile_Feature) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Tile_Feature) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Tile_Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Tile_Feature) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Tile_Feature) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Feature) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Tile_Feature proto.InternalMessageInfo

const Default_Tile_Feature_Id uint64 = 0
const Default_Tile_Feature_Type Tile_GeomType = Tile_UNKNOWN

func (m *Tile_Feature) GetId() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Feature) GetTags() []uint32 { _ = "STUB: not implemented"; return nil }

func (m *Tile_Feature) GetType() Tile_GeomType {
	_ = "STUB: not implemented"
	return *new(Tile_GeomType)
}

func (m *Tile_Feature) GetGeometry() []uint32 { _ = "STUB: not implemented"; return nil }

type Tile_Layer struct {
	// Any compliant implementation must first read the version
	// number encoded in this message and choose the correct
	// implementation for this version number before proceeding to
	// decode other parts of this message.
	Version *uint32 `protobuf:"varint,15,req,name=version,def=1" json:"version,omitempty"`
	Name    *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// The actual features in this tile.
	Features []*Tile_Feature `protobuf:"bytes,2,rep,name=features" json:"features,omitempty"`
	// Dictionary encoding for keys
	Keys []string `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
	// Dictionary encoding for values
	Values []*Tile_Value `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
	// The bounding box in this tile spans from 0..4095 units
	Extent                       *uint32  `protobuf:"varint,5,opt,name=extent,def=4096" json:"extent,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Tile_Layer) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Tile_Layer) String() string            { _ = "STUB: not implemented"; return "" }
func (*Tile_Layer) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Tile_Layer) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var extRange_Tile_Layer = []proto.ExtensionRange{
	{Start: 16, End: 536870911},
}

func (*Tile_Layer) ExtensionRangeArray() []proto.ExtensionRange {
	_ = "STUB: not implemented"
	return nil
}

func (m *Tile_Layer) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Tile_Layer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Tile_Layer) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Tile_Layer) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Layer) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Tile_Layer proto.InternalMessageInfo

const Default_Tile_Layer_Version uint32 = 1
const Default_Tile_Layer_Extent uint32 = 4096

func (m *Tile_Layer) GetVersion() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Layer) GetName() string { _ = "STUB: not implemented"; return "" }

func (m *Tile_Layer) GetFeatures() []*Tile_Feature { _ = "STUB: not implemented"; return nil }

func (m *Tile_Layer) GetKeys() []string { _ = "STUB: not implemented"; return nil }

func (m *Tile_Layer) GetValues() []*Tile_Value { _ = "STUB: not implemented"; return nil }

func (m *Tile_Layer) GetExtent() uint32 { _ = "STUB: not implemented"; return 0 }

func init() {
	proto.RegisterEnum("vector_tile.Tile_GeomType", Tile_GeomType_name, Tile_GeomType_value)
	proto.RegisterType((*Tile)(nil), "vector_tile.Tile")
	proto.RegisterType((*Tile_Value)(nil), "vector_tile.Tile.Value")
	proto.RegisterType((*Tile_Feature)(nil), "vector_tile.Tile.Feature")
	proto.RegisterType((*Tile_Layer)(nil), "vector_tile.Tile.Layer")
}

func init() { proto.RegisterFile("vector_tile.proto", fileDescriptor_ca433dd0d9fb7008) }

var fileDescriptor_ca433dd0d9fb7008 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x4e, 0xb2, 0x75, 0x26, 0xb4, 0x64, 0x7d, 0x80, 0xd2, 0x85, 0x62, 0xf6, 0x64, 0xf5,
	0x50, 0x96, 0x8a, 0x1f, 0xd1, 0x0b, 0x68, 0x25, 0x28, 0x15, 0x55, 0xba, 0x32, 0x05, 0xc4, 0x69,
	0x95, 0xa5, 0xde, 0x2a, 0x22, 0x8d, 0xab, 0xc4, 0xad, 0xc8, 0xad, 0x2f, 0xc0, 0x7b, 0x71, 0xe4,
	0x01, 0x38, 0xa0, 0xf2, 0x06, 0x3c, 0x01, 0x8a, 0x93, 0x76, 0x2b, 0x2d, 0x37, 0xfb, 0xfb, 0xbe,
	0xf9, 0x34, 0xf3, 0xcd, 0xc0, 0xe1, 0x4a, 0x7e, 0xd1, 0x2a, 0x3d, 0xd7, 0x51, 0x2c, 0xbb, 0x8b,
	0x54, 0x69, 0x45, 0xbd, 0x3d, 0xe8, 0xf8, 0x8f, 0x03, 0xf6, 0x24, 0x8a, 0x25, 0x7d, 0x04, 0x07,
	0x71, 0x98, 0xcb, 0x34, 0x6b, 0x5a, 0xcc, 0xe2, 0x5e, 0xef, 0x4e, 0x77, 0xbf, 0xb2, 0x90, 0x74,
	0x47, 0x05, 0x2f, 0x2a, 0x59, 0xeb, 0x2f, 0x02, 0xe7, 0x63, 0x18, 0x2f, 0x25, 0x7d, 0x08, 0x37,
	0x33, 0x9d, 0x46, 0xc9, 0xec, 0x7c, 0x55, 0xfc, 0x9b, 0x88, 0x21, 0xee, 0x0a, 0xaf, 0xc4, 0x4a,
	0xc9, 0x03, 0xf0, 0x2e, 0x63, 0x15, 0xea, 0x4a, 0x81, 0x19, 0xe2, 0x58, 0x80, 0x81, 0x76, 0x1e,
	0x53, 0xb5, 0xbc, 0x88, 0x65, 0xa5, 0xb0, 0x18, 0xe2, 0x48, 0x78, 0x25, 0x56, 0x4a, 0x8e, 0xc0,
	0x8d, 0x92, 0xad, 0x83, 0xcd, 0x10, 0xb7, 0x04, 0x89, 0x92, 0xaa, 0xfe, 0x3e, 0xc0, 0xf2, 0x8a,
	0x75, 0x18, 0xe2, 0xb6, 0x70, 0x97, 0xfb, 0x74, 0x76, 0x45, 0x1f, 0x30, 0xc4, 0xa9, 0x70, 0xb3,
	0x7d, 0xfa, 0x42, 0xa9, 0xb8, 0xa2, 0x6b, 0x0c, 0x71, 0x22, 0xdc, 0x02, 0x31, 0x74, 0x87, 0x10,
	0xe2, 0xaf, 0xd7, 0xeb, 0x35, 0x6e, 0x7d, 0x47, 0x50, 0x7b, 0x23, 0x43, 0xbd, 0x4c, 0x25, 0x3d,
	0x04, 0x1c, 0x4d, 0xcd, 0xb0, 0x76, 0x1f, 0x9d, 0x08, 0x1c, 0x4d, 0xe9, 0x6d, 0xb0, 0x75, 0x38,
	0xcb, 0x9a, 0x98, 0x59, 0xbc, 0x7e, 0x8a, 0x7d, 0x24, 0xcc, 0x9f, 0x3e, 0x07, 0x5b, 0xe7, 0x8b,
	0x72, 0xaa, 0x46, 0xaf, 0x75, 0x3d, 0xda, 0x81, 0x54, 0xf3, 0x49, 0xbe, 0x90, 0xfd, 0xda, 0x87,
	0xe0, 0x5d, 0x30, 0xfe, 0x14, 0x08, 0x53, 0x40, 0xdb, 0x40, 0x66, 0x52, 0xcd, 0xa5, 0x4e, 0xf3,
	0xa6, 0xbd, 0x33, 0xdd, 0x61, 0xad, 0x5f, 0x08, 0x1c, 0xb3, 0x16, 0x7a, 0x04, 0xb5, 0x95, 0x4c,
	0xb3, 0x48, 0x25, 0xcd, 0x5b, 0x0c, 0xf3, 0x7a, 0x1f, 0x3d, 0x16, 0x5b, 0x84, 0x52, 0xb0, 0x93,
	0x70, 0x5e, 0x6c, 0x06, 0x73, 0x57, 0x98, 0x37, 0x7d, 0x0a, 0xe4, 0xb2, 0x9c, 0xa4, 0xec, 0xd7,
	0xeb, 0xdd, 0xbd, 0xde, 0x57, 0x35, 0xab, 0xd8, 0x49, 0x0b, 0xab, 0xaf, 0x32, 0x2f, 0xaf, 0xc4,
	0x15, 0xe6, 0x5d, 0xdc, 0x8e, 0x49, 0x2e, 0x33, 0x3d, 0xfe, 0xf7, 0x76, 0x4c, 0x90, 0xa2, 0x92,
	0xd1, 0x7b, 0x70, 0x20, 0xbf, 0x69, 0x99, 0x68, 0xb3, 0xa9, 0x7a, 0xdf, 0x7e, 0x72, 0xf2, 0xe2,
	0x99, 0xa8, 0xb0, 0x0e, 0x21, 0x7e, 0x19, 0xf7, 0xf1, 0x4b, 0x20, 0xdb, 0x64, 0xa8, 0x07, 0xdb,
	0x6c, 0xfc, 0x1b, 0xd4, 0x05, 0xe7, 0x6c, 0x3c, 0x0c, 0x26, 0x3e, 0xa2, 0x0d, 0x80, 0xd1, 0x30,
	0x78, 0xfd, 0x7e, 0x22, 0x86, 0xc1, 0xc0, 0xc7, 0x85, 0xee, 0x6c, 0x3c, 0xfa, 0x3c, 0x18, 0x07,
	0xbe, 0xd5, 0x71, 0x0a, 0xab, 0x57, 0xa7, 0x8d, 0x1f, 0x9b, 0x36, 0xfa, 0xb9, 0x69, 0xa3, 0xdf,
	0x9b, 0x36, 0x7a, 0x6b, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x3c, 0xd7, 0x26, 0x16, 0x03,
	0x00, 0x00,
}

func (m *Tile) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Tile) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Tile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Tile_Value) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Tile_Value) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Tile_Value) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Tile_Feature) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Tile_Feature) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Tile_Feature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Tile_Layer) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Tile_Layer) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Tile_Layer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintVectorTile(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Tile) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Value) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Feature) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Tile_Layer) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovVectorTile(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozVectorTile(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Tile) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Tile_Value) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Tile_Feature) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Tile_Layer) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipVectorTile(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthVectorTile        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVectorTile          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVectorTile = fmt.Errorf("proto: unexpected end of group")
)
